
name: Tech Radar

on:
  push:
    branches: ['main']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate_tech_radar:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Tech Radar
        id: deployment
        uses: flexion/tech-radar-generator@v0.1.3
        with:
          radar_name: My Radar
          directory: ./docs             # Directory where the radar directory is located
          base_path: /my-repo/techradar # Path after domain, used to generate assets
          base_dir: techradar             # Location for assets for GH Pages
          publish_to_pages: 'true'
